package trader;

import javax.swing.JOptionPane;
import mockstock.db.Trader;
import mockstock.db.enumeration.UserRight;
import mockstock.db.enumeration.UserStatus;
import mockstock.ejb.front.AdminRemote;
import mockstock.ejb.front.TraderFacadeRemote;
import util.Utils;

/**
 *
 * @author felmas
 */
public class UserAddGUI extends javax.swing.JFrame {

    private JoinMarketGUI parent;
    
    private Trader admin;
    
    /* This is bonus to move between windows */
    private AdminRemote adminBean;
    private TraderFacadeRemote traderFacade;
    
    /**
     * Creates new form UserAddGUI
     */
    public UserAddGUI(AdminRemote adminBean, TraderFacadeRemote traderFacade, Trader admin, JoinMarketGUI parent) {
        this.parent = parent;
        
        this.admin = admin;
        
        this.adminBean = adminBean;
        this.traderFacade = traderFacade;
        initComponents();
        
        this.statusCheckBox.add("Activated");
        this.statusCheckBox.add("Deactivated");
        this.statusCheckBox.select("Activated");
        
        this.adminCheckBox.setSelected(false);
        this.setTitle("Admin New User Add View");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        repasswordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        adminCheckBox = new javax.swing.JCheckBox();
        statusCheckBox = new java.awt.Choice();
        addUserButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        emailEditBox = new javax.swing.JTextField();
        nameEditBox = new javax.swing.JTextField();
        surnameEditBox = new javax.swing.JTextField();
        passwordEditBox = new javax.swing.JPasswordField();
        repasswordEditBox = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        emailLabel.setText("Email:");

        passwordLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        passwordLabel.setText("Password:");

        repasswordLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        repasswordLabel.setText("Repassword:");

        nameLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        nameLabel.setText("Name:");

        surnameLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        surnameLabel.setText("Surname:");

        adminCheckBox.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        adminCheckBox.setText("Admin");

        statusCheckBox.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 240, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(passwordLabel)
                            .addComponent(repasswordLabel)
                            .addComponent(nameLabel)
                            .addComponent(surnameLabel)
                            .addComponent(adminCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordEditBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(repasswordEditBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameEditBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(surnameEditBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(statusCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(emailEditBox))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailEditBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordEditBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repasswordLabel)
                    .addComponent(repasswordEditBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameEditBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLabel)
                    .addComponent(surnameEditBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminCheckBox))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(cancelButton))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String email = emailEditBox.getText();
        String password = new String(passwordEditBox.getPassword());
        String repassword = new String(repasswordEditBox.getPassword());
        
        if(Utils.isEmail(email)) {
            if(!traderFacade.verifyEmailRemote(email)) {
                if(password != null && !password.isEmpty() && password.length() >= 6) {
                    if(password.equals(repassword)) {

                        mockstock.db.Trader trader = new mockstock.db.Trader();
                        trader.setEmail(email);
                        trader.setPassword(Utils.encryptPassword(password));
                        trader.setFirstname(nameEditBox.getText());
                        trader.setLastname(surnameEditBox.getText());

                        if(statusCheckBox.getSelectedItem().equals("Activated")) {
                            trader.setStatus(UserStatus.ACTIVATED);
                        } else {
                            trader.setStatus(UserStatus.NOT_ACTIVE);
                        }
                        
                        if(adminCheckBox.isSelected()) {
                            trader.setUsrgroup(UserRight.ADMIN);
                        } else {
                            trader.setUsrgroup(UserRight.USER);
                        }

                        traderFacade.addTraderRemote(trader);
                        
                        JOptionPane.showMessageDialog(this, "User is successfully added!");
                        
                        AdminGUI adminGUI = new AdminGUI(adminBean, traderFacade, admin, parent);
                        Utils.setLocation(adminGUI);
                        adminGUI.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Passwords don't match\nPlease be sure that you enter correctly!");
                        if(!passwordEditBox.requestFocusInWindow()) passwordEditBox.selectAll();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password\nPassword cannot be less than 6 characters!");
                    if(!passwordEditBox.requestFocusInWindow()) passwordEditBox.selectAll();
                }
            } else {
                JOptionPane.showMessageDialog(this, "This email is already in use!");
                if(!emailEditBox.requestFocusInWindow()) emailEditBox.selectAll();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid email!");
            if(!emailEditBox.requestFocusInWindow()) emailEditBox.selectAll();
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        AdminGUI adminGUI = new AdminGUI(adminBean, traderFacade, admin, parent);
        Utils.setLocation(adminGUI);
        adminGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailEditBox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameEditBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordEditBox;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField repasswordEditBox;
    private javax.swing.JLabel repasswordLabel;
    private java.awt.Choice statusCheckBox;
    private javax.swing.JTextField surnameEditBox;
    private javax.swing.JLabel surnameLabel;
    // End of variables declaration//GEN-END:variables
}
